### PR TITLE
Link to maintainers file

### PR DESCRIPTION
**Pull request by xmulligan**

### CODE REVIEW

**Comment by xmulligan** [comment]
@ti-mo or @lorenz  can you help here?

**Comment by ti-mo** [comment]
I think @lmb is the Lorenz you're looking for. :) Any context around this might expedite things.

**Comment by xmulligan** [comment]
Sorry my mistake!

I made this PR because we would like to centralize where we are keeping track of maintainers across the project. You can see I'm doing the same thing in cilium/cilium https://github.com/cilium/cilium/pull/24124

**Comment by ti-mo** [comment]
Sure, we can centralize this. Thanks!

**Comment by xmulligan** [comment]
Thank you!

**Pull request merged**
