### PR TITLE
uprobe_in_go116

### PR DESCRIPTION
**Pull request by liyan-ah**
uprobe_in_go116

### CODE REVIEW

**Comment by liyan-ah** [comment]
it's useful to add go1.16 examples. here add one uprobe example, and would add go1.17 example later if necessary.

**Comment by liyan-ah** [comment]
Does arm64 bpf2go compiled results are necessary? I have no arm64 here.

**Comment by liyan-ah** [comment]
@lmb @tklauser

**Comment by lmb** [comment]
Hi @liyan-ah, thanks for your PR. Can you explain what exactly you want to demonstrate? Superficially it seems quite similar to the uretprobe example.

**Comment by liyan-ah** [comment]
> 

Hi @lmb , thanks for your replay. The demo is build based on uretprobe. What I want to demonstrate is provide a uprobe demo in go.
I just worked in a project need to use eBPF attach some golang process, and found it's difficult to get examples for golang. Although I worked out my project, and think it's a good idea to provide an example.
Hope this PR save some time for new learners.

Maybe examples like this PR or bpf-map set/get between user-code and bpf-code are simple, but it do save new learners' time. I use bpftrace as well. Benefit from the simple [Reference Guide](https://github.com/iovisor/bpftrace/blob/master/docs/reference_guide.md), it's pretty simple to build code. Cilium-ebpf seems lack of such document and use examples to provide such guide. More elementary codes may be needed.

Sorry for my poor English. Have a good day.

**Comment by liyan-ah** [comment]
@lmb

**Comment by florianl** [comment]
From my point of view examples in cilium/ebpf should focus on the functionality [cilium/ebpf](https://github.com/cilium/ebpf) provides. With this in mind, I do think this PR does not provide a hands on for new users showcasing the functionality of [cilium/ebpf](https://github.com/cilium/ebpf). As pointed out earlier it is based on the already existing example of [uretprobe](https://github.com/cilium/ebpf/tree/master/examples/uretprobe).

The additional value this PR might showcase, which is from my perspective the extraction of arguments in eBPF, is not related to the loader functionality of [cilium/ebpf](https://github.com/cilium/ebpf). If the idea is to provide similar tooling like [iovisor/bpftrace](https://github.com/iovisor/bpftrace) based on [cilium/ebpf](https://github.com/cilium/ebpf) then I think a dedicated repository would be best.

**Comment by liyan-ah** [comment]
> From my point of view examples in cilium/ebpf should focus on the functionality [cilium/ebpf](https://github.com/cilium/ebpf) provides. With this in mind, I do think this PR does not provide a hands on for new users showcasing the functionality of [cilium/ebpf](https://github.com/cilium/ebpf). As pointed out earlier it is based on the already existing example of [uretprobe](https://github.com/cilium/ebpf/tree/master/examples/uretprobe).
> 
> The additional value this PR might showcase, which is from my perspective the extraction of arguments in eBPF, is not related to the loader functionality of [cilium/ebpf](https://github.com/cilium/ebpf). If the idea is to provide similar tooling like [iovisor/bpftrace](https://github.com/iovisor/bpftrace) based on [cilium/ebpf](https://github.com/cilium/ebpf) then I think a dedicated repository would be best.

Thanks for your reply. Maybe a new repo is needed.

**Pull request closed without merging**
