### PR TITLE
Look for Linux note in all elf note sections instead of just the first one

### PR DESCRIPTION
**Pull request by paulcacheux**
When looking for the Linux version, we currently look for the "Linux" note in the vdso.

For strange and unknown reasons, on some kernels (specially on a Container Optimized OS v85 with a 5.4.x kernel), the `.rodata` can also have an elf section type of `SHT_NOTE`.

This means that only looking at the first note section can result in just looking at the wrong section.

This PR fixes this issue by looking at all the note sections.

### CODE REVIEW

**Comment by lmb** [comment]
Thanks for your PR! Could you dump the vdso that is causing the problem into `testdata` and extend `TestLinuxVersionCodeEmbedded`?

**Comment by paulcacheux** [comment]
Good point, I will do that

**Review by lmb — APPROVED** [review]
Thanks!

**Comment by ti-mo** [comment]
Thanks!

**Comment by lmb** [comment]
We don't have a specific release cycle. Since there are only bugfixes on master I tagged 0.8.1 for you.

**Pull request merged**
