### PR TITLE
map: Add PinPathFinal bool to MapOptions

### PR DESCRIPTION
**Pull request by olsajiri**
Currently the final pin path is composed of the PinPath
option joined with map name.
    
We have a use case where we want to specify specific
name for the map pin file.
    
Adding PinPathFinal bool that assuments the provided
PinPath option is the final pin path.
    
Signed-off-by: Jiri Olsa <jolsa@kernel.org>

### CODE REVIEW

**Review by lmb — COMMENTED** [review]
This breaks when passing MapOptions.PinPathFinal to NewCollection with multiple maps. Can you describe what your use case is? Maybe there is a different way to solve this.

**Comment by olsajiri** [comment]
we have 2 programs that can be load multiple times and they need to share specific
map in between them, but not with other instances  of such 2 programs loaded,
so we add specific pin file prefix for such couple

one option with the current code is to use specific directory, but would mean bigger
changes and it seemed to me ebpf library should be able to pin under specific name
anyway

current code uses Map::Pin which works just fine, but there's checkCompatibility,
in the path of NewMapWithOptions->newMapWithOptions->PinByName that
I wanted to take advantage of when starting on top of previous pinned maps to
make sure the spec still matches, but it's easy enough to add that to our code if
we can't go with this change

**Comment by lmb** [comment]
> there's checkCompatibility,
> in the path of NewMapWithOptions->newMapWithOptions->PinByName that
> I wanted to take advantage of when starting on top of previous pinned maps to
> make sure the spec still matches

We could expose that function I think. Maybe `Map.IsCompatibleWith(*MapSpec) error` would make more sense for a public API though?

**Comment by olsajiri** [comment]
> ok, that would work.. will make another PR for that, thanks

https://github.com/cilium/ebpf/pull/858

**Pull request closed without merging**
