### PR TITLE
CI: run tests on arm64

### LINKED ISSUE #266: aarch64 / arm64 support
I see failure in running [kprobe example](https://github.com/cilium/ebpf/tree/master/examples/kprobe) for aarch64 kernel version `4.19.113`

```
GOOS=linux GOARCH=arm64 go build -o ebpf-kprobe

./ebpf-kprobe 
2021/03/25 22:03:40 error while loading objects: field KprobeExecve: program kprobe_execve: load program without BTF: invalid argument
```

looks like `BPF_PROG_LOAD` is [failing](https://gist.github.com/shrkamat/d24a81505833391f95cbe81f2c865c1a#file-epbf-kprobe-fail-L406)

### PR DESCRIPTION
**Pull request by lmb**
Use the actuated runners provided by the CNCF to run the testsuite on arm64. These runners do not support nested KVM and therefore we can run the VM tests there.

Fixes #266

### CODE REVIEW

**Comment by alexellis** [comment]
Hi @lmb we got BFP/BTF working enough to run Cilium with KinD and for Tetragon tests to pass, but I'm not sure if there's anything else we need to enable for this repo?

>    kprobe_test.go:29: load program: operation not permitted (MEMLOCK may be too low, consider rlimit.RemoveMemlock)

I'm not sure what his memory lock error is about, but the Kernel version is currently capped at 5.10.201 for arm64 if that helps.

Are there `CONFIG_` settings that you're expecting that you've not seen here?

Alex

**Comment by lmb** [comment]
@alexellis thanks for taking a look! From the failing tests we need the following:

- [CONFIG_XDP_SOCKETS](https://elixir.bootlin.com/linux/latest/source/include/linux/bpf_types.h#L119)
- [CONFIG_BPF_LIRC_MODE2](https://elixir.bootlin.com/linux/latest/source/include/linux/bpf_types.h#L61)
- CONFIG_PERF_EVENTS

**Comment by alexellis** [comment]
Hi @lmb that is enabled in the Kernel, you can check what's available by inspecting the config file as per:

https://github.com/cncf-tests/show-config/blob/master/.github/workflows/info.yaml

Click "View raw events" to see the full details.

You can also start an SSH debug session to explore more - https://docs.actuated.dev/tasks/debug-ssh/

Alex

**Comment by lmb** [comment]
Pretty sure this is hitting https://elixir.bootlin.com/linux/latest/source/arch/arm64/kernel/probes/uprobes.c#L42 in the kernel since other uprobe / kprobe tests work fine.

**Comment by alexellis** [comment]
I see a note there that says:

`	/* TODO: Currently we do not support AARCH32 instruction probing */`

**Comment by lmb** [comment]
@alexellis no changes on your side necessary I think! See https://github.com/cilium/ebpf/pull/1245/commits/e3b056ae1b2ccbd463d8f1233f453318c49c9dd0

**Comment by lmb** [comment]
@alexellis thanks for all your help! Is there any chance we can get nested KVM support? Over the long run we really need it to be able to control the enabled kernel features.

**Comment by mtardy** [comment]
Very glad to see this working 🎉  congrats everyone!

**Comment by dneary** [comment]
> @alexellis thanks for all your help! Is there any chance we can get nested KVM support? Over the long run we really need it to be able to control the enabled kernel features.

While Ampere Altra supports FEAT_NV2, I don't think the patches to enable nested virtualization in the Linux kernel have been merged yet. There is a patchset being curated on the LKML: https://patchwork.kernel.org/project/linux-arm-kernel/cover/20190621093843.220980-1-marc.zyngier@arm.com/

**Comment by alexellis** [comment]
@mtardy @lmb we have a 6.1.90 Kernel available for actuated on arm64, is this of interest? Would it be of benefit to migrate from 5.10.201?

https://docs.actuated.dev/faq/#what-kernel-version-is-being-used

**Comment by lmb** [comment]
Happy to give it a try if you can link to some instructions how to use the experimental runners.

**Comment by alexellis** [comment]
Hi @lmb we did a gradual rollout and didn't hear any complaints so have switched all servers over now, let us know if you experience any issues with your Arm64 builds that run on actuated.

**Comment by alexellis** [comment]
Do you know which CONFIG_ settings go with bpf_link_kprobe_multi?

**Comment by lmb** [comment]
I think it may be up to `CONFIG_FPROBE` which kprobe_multi relies on IIRC. @olsajiri could you confirm?

**Comment by alexellis** [comment]
We don't have `CONFIG_FPROBE` so that seems likely.

**Comment by alexellis** [comment]
I've rolled out this change if you are able to restart the failed job?

**Comment by lmb** [comment]
Still happening, let's continue in https://github.com/cilium/ebpf/issues/1460

**Comment by mtardy** [comment]
> Hi @lmb we did a gradual rollout and didn't hear any complaints so have switched all servers over now, let us know if you experience any issues with your Arm64 builds that run on actuated.

Just adding here that it seems that tetragon is okay with the new kernel version, thank you for the information.

**Comment by alexellis** [comment]
@mtardy thanks for the comment. I would expect it to be. I did run through the quickstart and made sure it worked for Cilium and Tetragon.

**Pull request merged**
