### PR TITLE
link: close tracefs event if perf event cannot be opened

### PR DESCRIPTION
**Pull request by nashuiliang**
When getTraceEventID() or openTracepointPerfEvent() returns an error,
tracefs event (e.g. /sys/kernel/debug/tracing/events/<group>), which has
been created by createTraceFSProbeEvent(), is not cleaned up.

Signed-off-by: Chuang Wang <nashuiliang@gmail.com>

### CODE REVIEW

**Review by mmat11 — APPROVED** [review]
I remember pointing this out in the initial Kprobe implementation, here's the discussion: https://github.com/cilium/ebpf/pull/265#discussion_r602535385. I have no strong opinion but prefer cleaning it up /cc @ti-mo

**Comment by nashuiliang** [comment]
Thanks, I read the discussion: https://github.com/cilium/ebpf/pull/265#discussion_r602535385.

I should briefly describe my scene：
> When **livepatch** and **kprobe** are using the same kernel function X, tracefs event (e.g. /sys/kernel/debug/tracing/events/), which has been created by createTraceFSProbeEvent(), cannot be enabled by syscall `perf_event_open`

Therefore, I should add `closeTraceFSProbeEvent()` on failed `openTracepointPerfEvent()`.
Hmm, I saw `getTraceEventID()` as well, and added it by the way, although I thought it might not return an error.

**Comment by nashuiliang** [comment]
@ti-mo Wow, cool!

The test method is more complicated. It can be triggered manually, and it is difficult to write test code at the same time.

**Comment by lmb** [comment]
> I should briefly describe my scene:
> > When **livepatch** and **kprobe** are using the same kernel function X, tracefs event (e.g. /sys/kernel/debug/tracing/events/), which has been created by createTraceFSProbeEvent(), cannot be enabled by syscall `perf_event_open`.

Interesting! Out of curiosity, which errno do you get from perf_event_open?

**Review by lmb — APPROVED** [review]

**Comment by nashuiliang** [comment]
Error: `opening tracepoint perf event: device or resource busy`.
Errno: `-EBUSY`

**Pull request merged**
